### ISSUE TITLE
This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by Davidzhu001** [SproutVideo/sproutvideo-rb#7]
Good morning guys,

I have a question regard to the protocols:

I get the api from the playlist, there is a embed_code to grab the iframe work.

However, the protocols of it is http and the rest of the api calls are under https.

So, it failed on my site.

Is there any way to correct it?

I tried to change my playlist by using the ssl methods, but it didn't change the api part.

**Comment by podman** [comment]
Hi David,

Thanks for writing in.

This sort of request would be best handled by our support team as it is not an issue with the ruby API client but the data that is being returned by the API itself.

Please send an email to support@sproutvideo.com and they'll help you address this issue.
